version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - "4000:4000"